# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: 'Backend'
    - name: Install Jetbrains HTTP client # See from https://blog.jetbrains.com/idea/2022/12/http-client-cli-run-requests-and-tests-on-ci/
      run: |
        curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest" 
        
        # Comes from https://askubuntu.com/a/86852
        unzip ijhttp.zip
        
        ls
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
