# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: 'Backend'

      # See https://github.com/marketplace/actions/docker-compose-action
      - name: Start DB
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          # Description: Path to compose file(s). It can be a list of files. It can be
          # absolute or relative to the current working directory (cwd).
          #
          # Default: ./docker-compose.yml
          compose-file: "./Backend/docker-compose.yml"

      - name: Start application
        run: |
          cd Backend
          npm i
          npm run server_ci &
          sleep 2

      # See:
      #  - https://blog.jetbrains.com/idea/2022/12/http-client-cli-run-requests-and-tests-on-ci/#running-requests-from-the-terminal
      #  - https://github.com/marketplace/actions/intellij-http-client-action
      - name: Run integration tests
        uses: madhead/intellij-http-client-action@latest
        with:
          insecure: true
          files: |-
            ./Backend/login_tests.http
